### ISSUE TITLE
Argument #2 ($array) must be of type array, string given (FEE - Dropzone)

### ISSUE THREAD

**Issue by tognit** [MetaModels/dropzone_file_upload#2]
Hallo zusammen

Contao 4.13.44
MM: dev-feature/2.3.0
MM-FFE: dev-feature/2.3.0
MM-Dropzone: dev-feature/2.3.0

Ich erhalte im Frontend die nachfolgende Meldung, dass da was mit einem Array nicht stimmt.

> Uncaught PHP Exception TypeError: "array_map(): Argument #2 ($array) must be of type array, string given" at /home/public_html/contao/contao_4.13_test/vendor/metamodels/dropzone_file_upload/src/EventListener/HandleDropzoneUpload.php line 228

Im Backend sind folgende Einstellungen im Attribute gemacht ...
![Dropzone-MetaModels](https://github.com/MetaModels/dropzone_file_upload/assets/1794459/f6f7b064-a3d4-419b-b911-5ea79d838ee5)

**Comment by zonky2** [comment]
kommt die Meldung auch, wenn man mehrere Dateien uploadet?

**Comment by tognit** [comment]
Kommt auch bei mehreren Dateien! 

Habe gerade gesehen, dass die Dateien hochgeladen und im Dateisystem gespeichert werden.
Aber nicht am Item hinzugefügt wurden.

**Comment by tognit** [comment]
Wenn man im Attribute "File" die Mehrfachauswahl aktiviert, kommt keine Meldung mehr.
![Metamodels-Mehrfachauswahl](https://github.com/MetaModels/dropzone_file_upload/assets/1794459/f087570c-7a87-4e4d-8da7-593264dc1a31)
Nur hat dann das Limit beim Dropzone kein einfluss mehr.

**Comment by zonky2** [comment]
Ich kann die Sache erst ab dem 01.07.2024 debuggen... ggf. versuchen, ein cast auf Array zu machen

```
$values    = \array_map('\Contao\StringUtil::binToUuid', (array) $model->getProperty($event->getProperty()->getName()));
```

**Comment by tognit** [comment]
Dann kommt im FE dann diese Meldung ...

`Property image (file) did not accept the value (The values differ. Encountered type string expected array (Found '��*�.��j' . "\0" . ' ' . "\0" . 'N', expected array ( 0 => '��*�.��j' . "\0" . ' ' . "\0" . 'N', 1 => '�+M�.��j' . "\0" . ' ' . "\0" . 'N', ))).`

**Comment by zonky2** [comment]
hmmm... schade - entweder selbst mal debuggen oder warten ...

**Comment by zonky2** [comment]
kann die Sache soweit nachstellen - leider nicht ad hoc fixen... scheint etwas komplizierter zu sein, da beim Upload drei verschiedene Repos zusammenarbeiten müssen

**Comment by zonky2** [comment]
@tognit - alle beteiligten Repos für das FEE wurden für MM 2.3 aktualisiert - auch der Single-Upload wurde gefixt und ist somit "un-Deprecated"
